name: pr2
description: "A Flutter application about game engines."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI и навигация
  flutter_bloc: ^9.1.0
  cupertino_icons: ^1.0.8

  # База данных
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.1
  path: ^1.8.3

  # DI
  get_it: ^7.6.0
  injectable: ^2.1.0

  # Дополнительные
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Генерация кода - используем одинаковые версии
  drift_dev: ^2.13.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700